spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ebankify
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false
  jpa:
    show-sql: true

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 1s   # Optional: adjust if needed
    socket-timeout: 30s      # Optional: adjust if needed
    repositories:
      enabled: true          # Enable Elasticsearch repositories
